os: osx
language: cpp

compiler: g++

script:
    - make
    - make run | grep "Total"
    - make run | grep "Free"
    - make run | grep "Active"
    - make run | grep "Inactive"
    - make run | grep "Wired"
    - make clean
